name: API CI

on:
  push:
    branches: [main]
    paths:
      - 'app/**'
      - 'requirements.txt'
      - '.github/workflows/api-ci.yml'

  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest

    env:
      ENVIRONMENT: ci
      MONGO_URI: mongodb://localhost:27017/test
      CORS_ORIGINS: http://localhost:5173

    steps:
      - name: Saludar
        run: echo "Hola desde GitHub Actions"

      - name: Ver fecha del runner
        run: date

      - name: Ver archivos disponibles
        run: ls -la
  repo-files:
    runs-on: ubuntu-latest
    steps:
      - name: Descargar codigo del repositorio
        uses: actions/checkout@v6

      - name: Ver archivos disponibles
        run: ls -la
